#!/bin/bash

# Store the content of ZVV stationboard in variable. Edit the numeric value after id= to change to another station.
SOURCE=$(curl http://transport.opendata.ch/v1/stationboard?id=008591285\&limit=5)

# Extract destination strings and store them in a file
echo $SOURCE | jshon -e stationboard -a -e to | sed 's/"//g' | sed 's/Zürich, //' > /home/alinea/conkystuff/zvv/targets

# Extract bus numbers and store them in a file
echo $SOURCE | jshon -e stationboard -a -e number | sed 's/"//g' > /home/alinea/conkystuff/zvv/numbers

# Convert timestamps to "minutes from now" 
TIMESTAMPS=$(echo $SOURCE | jsawk 'return this.stationboard' | jsawk 'return this.stop.departureTimestamp' | sed 's/\[//' | sed 's/\]//' | sed 's/,/\n/g' | sed 's/"//g') 

# clear "minutes from now" file
echo "" > /home/alinea/conkystuff/zvv/minutes

# store minutes from now in a file
for line in $TIMESTAMPS
do
    echo $(( ( $line - $(date +%s) ) / 60 )) >> /home/alinea/conkystuff/zvv/minutes
done
