#!/bin/bash

# make sure we can access the proper X display
export DISPLAY=:0

# get the Meteoswiss webpage and extract the json url
URL=$(curl http://www.meteoswiss.admin.ch/home.html?tab=overview | grep forecast-chart/version | sed -e 's/^.*url="//' | sed 's/"//' | head -n 1)

# get the json page and store in file
curl http://www.meteoswiss.admin.ch$URL > /home/alinea/conkystuff/meteo/weather

# call python script to read that file and generate fancy plot
python /home/alinea/conkystuff/meteo/generateplot.py
